/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JLabel;
import javax.swing.JPanel;
import view.components.RoundedBorders;

/**
 *
 * @author PC-Fredy
 */
public class QuestionsView extends javax.swing.JPanel {

    /**
     * Creates new form QuestionsView
     */
    public QuestionsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelQuestions = new javax.swing.JPanel();
        panelCurrentQuestion = new javax.swing.JPanel();
        panelQuestionContainer = new view.components.RoundedBorders();
        txtQuestion = new javax.swing.JLabel();
        descendingBar1 = new components.DescendingBar();
        panelAnswers = new javax.swing.JPanel();
        panelAnswer1 = new view.components.RoundedBorders();
        txtAnswer1 = new javax.swing.JLabel();
        panelAnswer3 = new view.components.RoundedBorders();
        txtAnswer3 = new javax.swing.JLabel();
        panelAnswer2 = new view.components.RoundedBorders();
        txtAnswer2 = new javax.swing.JLabel();

        panelQuestions.setBackground(new java.awt.Color(0, 15, 8));

        panelCurrentQuestion.setOpaque(false);

        panelQuestionContainer.setBackground(new java.awt.Color(180, 207, 176));
        panelQuestionContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 146));

        txtQuestion.setBackground(new java.awt.Color(0, 15, 8));
        txtQuestion.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        txtQuestion.setForeground(new java.awt.Color(255, 255, 255));
        txtQuestion.setText("jLabel1");
        txtQuestion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtQuestion.setMaximumSize(new java.awt.Dimension(760, 90));
        panelQuestionContainer.add(txtQuestion);

        javax.swing.GroupLayout descendingBar1Layout = new javax.swing.GroupLayout(descendingBar1);
        descendingBar1.setLayout(descendingBar1Layout);
        descendingBar1Layout.setHorizontalGroup(
            descendingBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        descendingBar1Layout.setVerticalGroup(
            descendingBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelCurrentQuestionLayout = new javax.swing.GroupLayout(panelCurrentQuestion);
        panelCurrentQuestion.setLayout(panelCurrentQuestionLayout);
        panelCurrentQuestionLayout.setHorizontalGroup(
            panelCurrentQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurrentQuestionLayout.createSequentialGroup()
                .addGroup(panelCurrentQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCurrentQuestionLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(panelQuestionContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCurrentQuestionLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(descendingBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120))
        );
        panelCurrentQuestionLayout.setVerticalGroup(
            panelCurrentQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurrentQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descendingBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelQuestionContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        panelAnswers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelAnswers.setOpaque(false);

        panelAnswer1.setBackground(new java.awt.Color(197, 33, 132));
        panelAnswer1.setLayout(new java.awt.GridLayout(1, 0));

        txtAnswer1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        txtAnswer1.setForeground(new java.awt.Color(255, 255, 255));
        txtAnswer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnswer1.setText("jLabel1");
        txtAnswer1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtAnswer1.setMaximumSize(new java.awt.Dimension(200, 100));
        panelAnswer1.add(txtAnswer1);

        panelAnswer3.setBackground(new java.awt.Color(249, 112, 248));
        panelAnswer3.setLayout(new java.awt.GridLayout(1, 0));

        txtAnswer3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        txtAnswer3.setForeground(new java.awt.Color(255, 255, 255));
        txtAnswer3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnswer3.setText("jLabel3");
        txtAnswer3.setMaximumSize(new java.awt.Dimension(200, 100));
        panelAnswer3.add(txtAnswer3);

        panelAnswer2.setBackground(new java.awt.Color(229, 116, 188));
        panelAnswer2.setLayout(new java.awt.GridLayout(1, 0));

        txtAnswer2.setBackground(new java.awt.Color(255, 255, 255));
        txtAnswer2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        txtAnswer2.setForeground(new java.awt.Color(255, 255, 255));
        txtAnswer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnswer2.setText("jLabel2");
        txtAnswer2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtAnswer2.setMaximumSize(new java.awt.Dimension(200, 100));
        panelAnswer2.add(txtAnswer2);

        javax.swing.GroupLayout panelAnswersLayout = new javax.swing.GroupLayout(panelAnswers);
        panelAnswers.setLayout(panelAnswersLayout);
        panelAnswersLayout.setHorizontalGroup(
            panelAnswersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnswersLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(panelAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 382, Short.MAX_VALUE)
                .addComponent(panelAnswer3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(panelAnswersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelAnswersLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelAnswer2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelAnswersLayout.setVerticalGroup(
            panelAnswersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnswersLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(panelAnswersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelAnswer3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(panelAnswersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelAnswersLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelAnswer2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelQuestionsLayout = new javax.swing.GroupLayout(panelQuestions);
        panelQuestions.setLayout(panelQuestionsLayout);
        panelQuestionsLayout.setHorizontalGroup(
            panelQuestionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCurrentQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelAnswers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelQuestionsLayout.setVerticalGroup(
            panelQuestionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuestionsLayout.createSequentialGroup()
                .addComponent(panelCurrentQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelAnswers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.DescendingBar descendingBar1;
    private view.components.RoundedBorders panelAnswer1;
    private view.components.RoundedBorders panelAnswer2;
    private view.components.RoundedBorders panelAnswer3;
    private javax.swing.JPanel panelAnswers;
    private javax.swing.JPanel panelCurrentQuestion;
    private view.components.RoundedBorders panelQuestionContainer;
    private javax.swing.JPanel panelQuestions;
    private javax.swing.JLabel txtAnswer1;
    private javax.swing.JLabel txtAnswer2;
    private javax.swing.JLabel txtAnswer3;
    private javax.swing.JLabel txtQuestion;
    // End of variables declaration//GEN-END:variables

    public void setTxtAnswer1(JLabel txtAnswer1) {
        this.txtAnswer1 = txtAnswer1;
    }

    public void setTxtAnswer2(JLabel txtAnswer2) {
        this.txtAnswer2 = txtAnswer2;
    }

    public void setTxtAnswer3(JLabel txtAnswer3) {
        this.txtAnswer3 = txtAnswer3;
    }

    public void setTxtQuestion(JLabel txtQuestion) {
        this.txtQuestion = txtQuestion;
    }

    public RoundedBorders getPanelAnswer1() {
        return panelAnswer1;
    }

    public RoundedBorders getPanelAnswer2() {
        return panelAnswer2;
    }

    public RoundedBorders getPanelAnswer3() {
        return panelAnswer3;
    }

    public JPanel getPanelQuestions() {
        return panelQuestions;
    }

    public JLabel getTxtAnswer1() {
        return txtAnswer1;
    }

    public JLabel getTxtAnswer2() {
        return txtAnswer2;
    }

    public JLabel getTxtAnswer3() {
        return txtAnswer3;
    }

    public JLabel getTxtQuestion() {
        return txtQuestion;
    }

    
    

}
