/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;
import view.components.RoundedBorders;

/**
 *
 * @author PC-Fredy
 */
public class UsernameView extends javax.swing.JPanel {

    /**
     * Creates new form UsernameView
     */
    public UsernameView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        usernamePanel = new view.components.RoundedBorders();
        usernameLabel = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnUsername = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 15, 8));

        mainPanel.setBackground(new java.awt.Color(0, 15, 8));

        usernamePanel.setBackground(new java.awt.Color(180, 207, 176));
        usernamePanel.setMaximumSize(new java.awt.Dimension(800, 300));
        usernamePanel.setMinimumSize(new java.awt.Dimension(800, 300));
        usernamePanel.setLayout(new java.awt.GridBagLayout());

        usernameLabel.setBackground(new java.awt.Color(0, 15, 8));
        usernameLabel.setFont(new java.awt.Font("Segoe UI Symbol", 0, 36)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(0, 15, 8));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Ingrese su nombre de usuario.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        usernamePanel.add(usernameLabel, gridBagConstraints);

        txtUsername.setBackground(new java.awt.Color(255, 255, 255));
        txtUsername.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(0, 15, 8));
        txtUsername.setOpaque(true);
        txtUsername.setPreferredSize(new java.awt.Dimension(300, 30));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 11, 0);
        usernamePanel.add(txtUsername, gridBagConstraints);

        btnUsername.setBackground(new java.awt.Color(249, 180, 237));
        btnUsername.setForeground(new java.awt.Color(255, 255, 255));
        btnUsername.setText("Aceptar");
        btnUsername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUsername.setBorderPainted(false);
        btnUsername.setOpaque(true);
        btnUsername.setPreferredSize(new java.awt.Dimension(100, 30));
        btnUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsernameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        usernamePanel.add(btnUsername, gridBagConstraints);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(usernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUsername;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JLabel usernameLabel;
    private view.components.RoundedBorders usernamePanel;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnUsername() {
        return btnUsername;
    }

    public JTextField getTxtUsername() {
        return txtUsername;
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public RoundedBorders getUsernamePanel() {
        return usernamePanel;
    }
    
    

    
}
